openapi: 3.0.0
info:
  title: User API
  description: API for managing user information
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: Production server
paths:
  /users/{userId}:
    get:
      summary: Get user by IDWTF
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to get
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  username:
                    type: string
                  email:
                    type: string
